/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Workflow = {
  _id: string;
  _type: "workflow";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  states?: Array<{
    id?: string;
    title?: string;
    chatOpen?: boolean;
    _type: "workflowStateDef";
    _key: string;
  }>;
  initialState?: string;
  transitions?: Array<{
    id?: string;
    title?: string;
    from?: string;
    to?: string;
    actors?: Array<string>;
    _type: "workflowTransitionDef";
    _key: string;
  }>;
};

export type RoundReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "round";
};

export type Message = {
  _id: string;
  _type: "message";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  round?: RoundReference;
  speechKey?: string;
  author?: string;
  body?: string;
  sentAt?: string;
};

export type Round = {
  _id: string;
  _type: "round";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  workflowState?: string;
  speeches?: Array<{
    name?: string;
    _type: "speech";
    _key: string;
  }>;
  workflowHistory?: Array<{
    transition?: string;
    from?: string;
    to?: string;
    actorType?: "agent" | "person";
    actorName?: string;
    at?: string;
    _type: "workflowEvent";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Workflow
  | RoundReference
  | Message
  | Round
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/sanity/queries.ts
// Variable: CHAT_OPEN_STATES_QUERY
// Query: *[_id == "workflow-round"][0].states[chatOpen == true].id
export type CHAT_OPEN_STATES_QUERY_RESULT = Array<string | null> | null;

// Source: ../web/src/sanity/queries.ts
// Variable: OPEN_ROUNDS_QUERY
// Query: *[_type == "round" && workflowState in *[_id == "workflow-round"][0].states[chatOpen == true].id]    | order(_updatedAt desc){      _id, title,      "stateTitle": *[_id == "workflow-round"][0].states[id == ^.workflowState][0].title    }
export type OPEN_ROUNDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  stateTitle: string | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: ROUND_QUERY
// Query: *[_type == "round" && _id == $id][0]{    _id, title, workflowState, speeches[]{ _key, name },    "stateTitle": *[_id == "workflow-round"][0].states[id == ^.workflowState][0].title,    "chatOpen": workflowState in *[_id == "workflow-round"][0].states[chatOpen == true].id  }
export type ROUND_QUERY_RESULT = {
  _id: string;
  title: string | null;
  workflowState: string | null;
  speeches: Array<{
    _key: string;
    name: string | null;
  }> | null;
  stateTitle: string | null;
  chatOpen: boolean | false | true | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: MESSAGES_QUERY
// Query: *[_type == "message" && round._ref == $id] | order(sentAt asc){ _id, author, body, sentAt, speechKey }
export type MESSAGES_QUERY_RESULT = Array<{
  _id: string;
  author: string | null;
  body: string | null;
  sentAt: string | null;
  speechKey: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_id == "workflow-round"][0].states[chatOpen == true].id': CHAT_OPEN_STATES_QUERY_RESULT;
    '*[_type == "round" && workflowState in *[_id == "workflow-round"][0].states[chatOpen == true].id]\n    | order(_updatedAt desc){\n      _id, title,\n      "stateTitle": *[_id == "workflow-round"][0].states[id == ^.workflowState][0].title\n    }': OPEN_ROUNDS_QUERY_RESULT;
    '*[_type == "round" && _id == $id][0]{\n    _id, title, workflowState, speeches[]{ _key, name },\n    "stateTitle": *[_id == "workflow-round"][0].states[id == ^.workflowState][0].title,\n    "chatOpen": workflowState in *[_id == "workflow-round"][0].states[chatOpen == true].id\n  }': ROUND_QUERY_RESULT;
    '*[_type == "message" && round._ref == $id] | order(sentAt asc){ _id, author, body, sentAt, speechKey }': MESSAGES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
